spring.application.name=rua
server.port=1428

# No toques ni compartas nada de estos 2 bloque
# Conexion base de datos
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:46179/rua
spring.datasource.username=springboot
spring.datasource.password=oxidado-azucar-union
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Envio de GMAILS
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#Logs
logging.level.org.springframework.mail=DEBUG