spring.application.name=rua
server.port=1428


# Datos NO validos para su uso

# No toques ni compartas nada de estos 2 bloque
# Conexion base de datos
#mysql -h centerbeam.proxy.rlwy.net -u springboot -p --port 46179 --protocol=TCP rua_v2
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:46179/rua_v2
spring.datasource.username=springboot
spring.datasource.password=${DBPASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Envio de GMAILS
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${MAILKEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#Logs
logging.level.org.springframework.mail=DEBUG
