spring.application.name=rua

# No toques ni compartas nada de este bloque, es para la conexion a la base de datos
spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:46179/rua
spring.datasource.username=springboot
spring.datasource.password=oxidado-azucar-union

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver