### Registrarse
POST http://localhost:1428/account/create
Content-Type: application/json

{
    "userName": "Tomas",
    "lastName1": "Jaures",
    "lastName2": "Painen",
    "mail": "t.jaures01@ufromail.cl",
    "hashedPassword": "12345678"
}

### Confirmar identidad (Cambiar el token)
GET http://localhost:1428/account/verify_email?token_verificacion=2c632766-622b-46fa-85c1-81995923649f

### Ver todos los bloques (Suponiendo que el calendario ID es 1)
GET http://localhost:1428/api/calendars/1/blocks
Accept: application/json

### Mover una clase (Suponiendo que el bloque ID es 1)
PATCH http://localhost:1428/api/calendars/blocks/1/move
Content-Type: application/json

{
  "weekDay": "TUE",
  "startHour": "10:00:00",
  "endHour": "11:30:00"
}

### Remover una clase
PATCH http://localhost:1428/api/calendars/blocks/1/remove

### Ver clases de la semana actual (Suponiendo calendario ID 1)
GET http://localhost:1428/api/calendar/1/classes
Accept: application/json

### Ver clases de una semana específica (Suponiendo semana 28)
GET http://localhost:1428/api/calendar/1/classes/week/28
Accept: application/json

### Generar las clases de la semana actual
POST http://localhost:1428/api/calendar/1/classes/generate

### Guardar el historial de cambios del calendario (Batch)
POST http://localhost:1428/api/calendar/1/changes
Content-Type: application/json

[
  {
    "action": "Add",
    "day": "MON",
    "startHour": "08:30:00",
    "endHour": "09:40:00",
    "moduleId": 5
  },
  {
    "action": "Remove",
    "blockId": 12
  }
]