### Registrarse
POST http://localhost:1428/account/create
Content-Type: application/json

{
    "userName": "Tomas",
    "lastName1": "Jaures",
    "lastName2": "Painen",
    "mail": "t.jaures01@ufromail.cl",
    "hashedPassword": "12345678"
}

### Confirmar identidad (Cambiar el token)
GET http://localhost:1428/account/verify_email?token_verificacion=2c632766-622b-46fa-85c1-81995923649f

### Ver todos los bloques (Suponiendo que el calendario ID es 1)
GET http://localhost:1428/api/calendars/1/blocks
Accept: application/json

### Mover una clase (Suponiendo que el bloque ID es 1)
PATCH http://localhost:1428/api/calendars/blocks/1/move
Content-Type: application/json

{
  "weekDay": "TUE",
  "startHour": "10:00:00",
  "endHour": "11:30:00"
}

### Remover una clase
PATCH http://localhost:1428/api/calendars/blocks/1/remove

###
## Ejercicio 4: Obtener las clases de la semana asociadas a un calendario
## CalendarController.getStudentCalendar
### Ver clases de la semana actual (Suponiendo calendario ID 1)
GET http://localhost:1428/api/calendar/1/classes
Accept: application/json

### Ver clases de una semana específica (Suponiendo semana 28)
GET http://localhost:1428/api/calendar/1/classes/week/28
Accept: application/json

### Generar las clases de la semana actual
POST http://localhost:1428/api/calendar/1/classes/generate

### Guardar el historial de cambios del calendario (Batch)
POST http://localhost:1428/api/calendar/1/changes
Content-Type: application/json

[
  {
    "action": "Add",
    "day": "MON",
    "startHour": "08:30:00",
    "endHour": "09:40:00",
    "moduleId": 5
  },
  {
    "action": "Remove",
    "blockId": 12
  }
]

###
# EJ1: Obtener asistencia de clases pasadas
## CalendarController.getAttendanceByWeek()
### Ver el estado de asistencia de las clases en una semana específica (Suponiendo calendario ID 1 y semana 28)
## Puede retornar:
### 200 OK con (List<WeekClassAttendanceInfoDTO>). Retorna el estado en el tiempo y si el alumno asistió.
### 400 Bad Request. Si es que no se encuentra la información del calendario en la BD o los parámetros son nulos.
GET http://localhost:1428/api/calendar/1/classesAttendance?weekId=28
Accept: application/json

###
# EJ2: Obtener asignaturas asociadas a un programa
## ProgramController.getProgramInfo()
### Cargar las asignaturas y sus módulos relacionados a un usuario (según su programa)
## Puede retornar:
### 200 OK con (List<ProgramInfoDTO>). Retorna la lista de asignaturas y sus módulos. Si no tiene, retorna lista vacía.
### 400 Bad Request. Si ocurre un error al procesar la petición en la base de datos.
GET http://localhost:1428/api/program/1/subjectsInfo
Accept: application/json

# EJ3: Persistir las modificaciones realizadas sobre el programa
## ProgramController.applyProgramChanges()
### guarda el historial de cambios (añadir, editar, eliminar) de asignaturas y módulos
## Puede retornar:
### 200 OK: Si todos los cambios se aplicaron exitosamente en la base de datos.
### 400 Bad Request: Si falla la transacción o hay datos inconsistentes.
POST http://localhost:1428/api/program/1/changes
Accept: application/json

###
# EJ4: Designar información académica a la Base de datos si un usuario escanea QR
## QrTokenController.decodeQr()
### Decodifica el QR, asigna asignaturas/bloques si el alumno es nuevo, y pasa asistencia.
## Puede retornar:
### 200 OK con Map (operated: boolean, attendance: Attendance).
### 400 Bad Request. Si el código QR es inválido, expiró o no se encuentra el correo del usuario.
POST http://localhost:1428/api/qr/decode?content=ingresa-uuid-del-token-aqui&email=alumno@ufromail.cl
Accept: application/json