sonar.projectKey=RUA
sonar.projectName=RUA

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.host.url=http://localhost:9000

sonar.token=squ_6112e19ca2a98bfca2735088d7e73a8da9f2c025

sonar.coverage.exclusions=src/test/java/**/*

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml