# Identificación del Proyecto
sonar.projectKey=RUA
sonar.projectName=RUA

# Conexión al servidor local de SonarQube
sonar.host.url=http://localhost:9000
# Nota: El token no se incluye aquí por seguridad, se pasa por la terminal.

# Rutas de compilación y cobertura (JaCoCo)
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml