sonar.projectKey=RUA
sonar.projectName=RUA

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.host.url=http://localhost:9000

sonar.coverage.exclusions=src/test/java/**/*

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
